title: Postman
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-postman-guide
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
offline: false
google_analytics: UA-166611802-1 #----> Optional
order: #----> Optional, order of documents

styling_options:
  primary_brand_color: '#100C55'
  logo_path: /assets/logo.svg
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/#!/5e8db1736d789b0011743202

hide_toolbar:
  sidebar: false
  pdf: true
  github: true

folders:
  - name: '/'
    title: 'A guide to all things Postman'
    subtitle: ''
    order:
      - "before-you-start.md" 
      - "twilio-sms.md"
      - "email.md"
      - "whatsapp.md"
      - "step-by-step-guide.md"
      - "poweruser.md"
      - "faq.md"
      - "release-notes.md"
      - "report-bug.md"


